#include <math.h>
#include <stdio.h>



// To calibrate the thermometer, reprogram clock with direct A/D converter result
// displaying.  Set Vlow to 0.  Set Vhigh to 4V.
// Attach resistor for 100`C and adjust gain until A/D gives 255.
// Attach resistor for 0`C and adjust Vlow until A/D gives 0.




// Table of temperatures C and kohms from the factory
static double factory_table[] = 
{
	0,    27.28,
	5,    22.05,
	10,   17.96,
	15,   14.68,
	20,   12.09,
	25,   10.00,
	30,   8.313,
	35,   6.941,
	40,   5.826,
	45,   4.912,
	50,   4.161,
	55,   3.537,
	60,   3.021,
	65,   2.589,
	70,   2.229,
	75,   1.924,
	80,   1.669,
	85,   1.451,
	90,   1.366,
	95,   1.108,
	100,  1        // Rounded because can't calibrate that precisely
};

// Measured A/D value for 100`C using resistors.
// MIN value must always be 0.
#define ANALOG_MAX 256.0

#define CUBE(x) ((x) * (x) * (x))



int main()
{
// Convert factory table to F and A/D results
	int entries = sizeof(factory_table) / sizeof(double) / 2;
	double new_table[entries * 2];
// The amount added to first A/D result to offset it to 0
	double factory_offset = ANALOG_MAX / factory_table[1];

	int i;
	for(i = 0; i < entries; i++)
	{
		double current_offset = factory_offset * (entries - i) / entries;
		new_table[i * 2] = factory_table[i * 2] * 9 / 5 + 32;
		new_table[i * 2 + 1] = ANALOG_MAX / factory_table[i * 2 + 1] - current_offset;
//printf("%f -> %f\n", new_table[i * 2], new_table[i * 2 + 1]);
	}

// Construct final table
	int j;
	printf("; thermister conversion table generated by thermotable.c\n");
	printf("thermotable:\n");
	for(i = 0; i < 256; i++)
	{
		double result = -256;

		for(j = 0; j < entries - 1; j++)
		{
			if(new_table[j * 2 + 1] <= i &&
				new_table[j * 2 + 3] > i)
			{
				result = ((double)i - new_table[j * 2 + 1]) /
					(new_table[j * 2 + 3] - new_table[j * 2 + 1]) *
					(new_table[j * 2 + 2] - new_table[j * 2]) +
					new_table[j * 2];
				break;
			}
		}

		if(result == -256)
		{
			if(i < new_table[1]) result = new_table[0];
			else
			if(i >= new_table[entries * 2 - 1]) result = new_table[entries * 2 - 2];
		}
		printf("	DATA D'%d'  ; %d\n", (int)result, i);
	}
	return 0;
}
